apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Prd Proton vault + database (same shape as dev, prd segment).
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/otel-collectors/clickhouse-password
    target:
      kind: ExternalSecret
      name: otel-clickhouse
  - patch: |
      - op: replace
        path: /spec/config/clickhouse/database
        value: otel_prd
    target:
      kind: OpenTelemetryCollector
      name: otel-gateway
