apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - element-secrets.yaml
  - wildcard-certificate.yaml
  - element-httproute.yaml
  - element-web.yaml
  - element-web-hpa.yaml
  - element-web-vpa.yaml
  - element-proxy.yaml
