apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Stg (prd values) external domain (zitadel.home-ops.yansyah.my.id).
  - patch: |
      - op: replace
        path: /spec/values/zitadel/configmapConfig/ExternalDomain
        value: zitadel.home-ops.yansyah.my.id
    target:
      kind: HelmRelease
      name: zitadel
