apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |
      - op: replace
        path: /spec/templates/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 100Gi
    target:
      kind: ClickHouseInstallation
      name: clickhouse
  # Prd S3 endpoint + vault refs + wildcard DNS.
  - patch: |
      - op: replace
        path: /spec/configuration/files/storage.xml
        value: |
          <yandex>
            <storage_configuration>
              <disks>
                <backups_s3>
                  <type>s3</type>
                  <endpoint>http://seaweed-main-s3.seaweedfs.svc.cluster.local:8333/clickhouse/</endpoint>
                  <access_key_id from_env="CLICKHOUSE_S3_ACCESS_KEY_ID"/>
                  <secret_access_key from_env="CLICKHOUSE_S3_SECRET_ACCESS_KEY"/>
                </backups_s3>
              </disks>
            </storage_configuration>
          </yandex>
    target:
      kind: ClickHouseInstallation
      name: clickhouse
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/clickhouse/s3-access-key-id
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/clickhouse/s3-secret-access-key
    target:
      kind: ExternalSecret
      name: clickhouse-s3-backup
  - patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "*.clickhouse.home-ops.yansyah.my.id"
    target:
      kind: Certificate
      name: wildcard-clickhouse
