apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Prd node NIC (enp45s0).
  - patch: |
      - op: replace
        path: /spec/config
        value: '{
            "cniVersion": "0.3.1",
            "name": "lan-dhcp",
            "type": "macvlan",
            "master": "enp45s0",
            "mode": "bridge",
            "ipam": { "type": "dhcp" }
          }'
    target:
      kind: NetworkAttachmentDefinition
      name: lan-dhcp
