apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Staging (prd values) secrets vault (pass://acme-prd-bdo1-talos-apps-01).
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/coder/oidc-client-secret
    target:
      kind: ExternalSecret
      name: coder-oidc
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/coder/db-connection-url
    target:
      kind: ExternalSecret
      name: coder-db-credentials
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/coder/db-password
    target:
      kind: ExternalSecret
      name: coder-db-app-secret
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/cnpg/s3-access-key-id
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/cnpg/s3-secret-access-key
    target:
      kind: ExternalSecret
      name: cnpg-s3-credentials
  - patch: |
      - op: replace
        path: /spec/backup/barmanObjectStore/endpointURL
        value: https://s3.seaweedfs.home-ops.yansyah.my.id
    target:
      kind: Cluster
      name: coder-db
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: coder.home-ops.yansyah.my.id
    target:
      kind: HTTPRoute
      name: coder-redirect
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: coder.home-ops.yansyah.my.id
    target:
      kind: HTTPRoute
      name: coder
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: "*.coder.home-ops.yansyah.my.id"
    target:
      kind: HTTPRoute
      name: coder-workspaces
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: "*.coder.home-ops.yansyah.my.id"
    target:
      kind: HTTPRoute
      name: coder-workspaces-redirect
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-prd-bdo1-talos-apps-01/cert-manager/cloudflare-api-token
    target:
      kind: ExternalSecret
      name: cloudflare-api-token
  - patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "coder.home-ops.yansyah.my.id"
    target:
      kind: Certificate
      name: coder-root
  - patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "*.coder.home-ops.yansyah.my.id"
    target:
      kind: Certificate
      name: coder-wildcard
