apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Prd HA scaling: controller + certController placeholders -> 2;
  # webhook stays singleton 1.
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
      - op: replace
        path: /spec/values/webhook/replicaCount
        value: 1
      - op: replace
        path: /spec/values/certController/replicaCount
        value: 2
    target:
      kind: HelmRelease
      name: external-secrets
