# win11-vm staged ISO policy (manual-only by hand-bump: the win11-vm
# VirtualMachine carries a REPLACE-ME placeholder source (BLOCKED until the
# licensed ISO is staged) and NO live inline $imagepolicy marker, so
# automation cannot rewrite it — no ImageRepository/ImagePolicy is shipped).
# `24H2` is a build label, NOT semver — never express it as a semver range.
# Stage per components/win11-vm/README.md "Windows 11 ISO import" and record
# the build there. No public changelog (licensed Microsoft ISO on local
# infra). Version source: the staged ISO behind spec.source in
# components/win11-vm/base/win11-vm.yaml (never committed).
# (Dropped 2026-09-27: a dead ImageRepository/ImagePolicy pair with an
# invalid `>=24H2` semver range and no matching live marker — automation PRs
# could never land.)
