apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mautrix-discord-secrets.yaml
  - mautrix-discord-rbac.yaml
  - bucketclaims.yaml
  - cosi-keys.yaml
  - mautrix-discord-db.yaml
  - mautrix-discord.yaml
  - mautrix-discord-vpa.yaml
