apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Prd external domain (zitadel.home-ops.yansyah.my.id).
  - patch: |
      - op: replace
        path: /spec/values/zitadel/configmapConfig/ExternalDomain
        value: zitadel.home-ops.yansyah.my.id
    target:
      kind: HelmRelease
      name: zitadel
  # Prd HA scaling: API placeholder -> 2, login stays singleton 1.
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
      - op: replace
        path: /spec/values/login/replicaCount
        value: 1
    target:
      kind: HelmRelease
      name: zitadel
