apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bucketclaims.yaml
  - cosi-keys.yaml
  - clickstack-secrets.yaml
  - clickstack-clickhouse.yaml
  - ferretdb-postgres.yaml
  - wildcard-certificate.yaml
  - clickstack-httproute.yaml
  - clickstack.yaml
  - ferretdb.yaml
  - oauth2-proxy.yaml
  - terraform.yaml
  - terraform-remote-state-rbac.yaml
