apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apprise-go-api-secrets.yaml
  - apprise-go-api.yaml
  - apprise-go-api-hpa.yaml
  - apprise-go-api-vpa.yaml
  - notifications.yaml
