apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oauth2-proxy-credentials.yaml
  - wildcard-certificate.yaml
  - httproute.yaml
  - flux-operator-ui.yaml
  - flux-operator-ui-hpa.yaml
  - flux-operator-ui-vpa.yaml
  - oauth2-proxy.yaml
  - oauth2-proxy-hpa.yaml
  - oauth2-proxy-vpa.yaml
  - terraform.yaml
  - zitadel-handoff-rbac.yaml
