apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hubble-secrets.yaml
  - wildcard-certificate.yaml
  - hubble-httproute.yaml
  - hubble-ui.yaml
  - oauth2-proxy.yaml
  - terraform.yaml
