apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Dev Coder URLs, OIDC issuer, mail domain, sign-in text.
  - patch: |
      - op: replace
        path: /spec/values/coder/env/0/value
        value: https://coder.homelab-dev.yansyah.my.id
      - op: replace
        path: /spec/values/coder/env/1/value
        value: "*.coder.homelab-dev.yansyah.my.id"
      - op: replace
        path: /spec/values/coder/env/4/value
        value: https://zitadel.homelab-dev.yansyah.my.id
      - op: replace
        path: /spec/values/coder/env/8/value
        value: homelab-dev.yansyah.my.id
      - op: replace
        path: /spec/values/coder/env/10/value
        value: Sign in with homelab-dev SSO
    target:
      kind: HelmRelease
      name: coder
