apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headlamp-secrets.yaml
  - wildcard-certificate.yaml
  - headlamp-rbac.yaml
  - headlamp-httproute.yaml
  - headlamp.yaml
