apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headlamp-secrets.yaml
  - wildcard-certificate.yaml
  - headlamp-rbac.yaml
  - headlamp-httproute.yaml
  - headlamp.yaml
  - headlamp-hpa.yaml
  - headlamp-vpa.yaml
  - terraform.yaml
  - zitadel-handoff-rbac.yaml
