apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest"
  components:
    - source-controller
    - source-watcher
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    size: medium
    multitenant: true
    tenantDefaultServiceAccount: flux
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: OCIRepository
    url: "oci://ghcr.io/lazygeniusman/home-ops/fleet"
    ref: "latest-stable"
    path: "clusters/home"
    pullSecret: "ghcr-auth"
  kustomize:
    patches:
      - target:
          kind: OCIRepository
          name: flux-system
        patch: |
          - op: add
            path: /spec/verify
            value:
              provider: cosign
              matchOIDCIdentity:
              - issuer: ^https://token\.actions\.githubusercontent\.com$
                subject: ^https://github\.com/LazyGeniusMan/home-ops/\.github/workflows/flux-fleet-release\.yaml@refs/tags/flux-fleet-v\d+\.\d+\.\d+$
