apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zitadel-secrets.yaml
  - zitadel-db.yaml
  - zitadel-cache.yaml
  - cosi-keys.yaml
  - bucketclaims.yaml
  - rclone-sync-buckets.yaml
  - wildcard-certificate.yaml
  - zitadel-httproute.yaml
  - zitadel-login-proxy.yaml
  - org-users.yaml
  - zitadel-bootstrap-handoff.yaml
