apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cloudflare-api-token.yaml
patches:
  # Dev S3 host + vault refs + wildcard DNS.
  - patch: |
      - op: replace
        path: /spec/args/0
        value: --s3_endpoint=s3.seaweedfs.homelab-dev.yansyah.my.id
    target:
      kind: Dragonfly
      name: dragonfly-base
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pass://acme-dev-bdo1-talos-apps-01/dragonfly/s3-access-key-id
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: pass://acme-dev-bdo1-talos-apps-01/dragonfly/s3-secret-access-key
    target:
      kind: ExternalSecret
      name: dragonfly-s3-credentials
  - patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "*.dragonfly.homelab-dev.yansyah.my.id"
    target:
      kind: Certificate
      name: wildcard-dragonfly
