apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # Prd proxy: Zitadel issuer, cookie domain, callback.
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --oidc-issuer-url=https://zitadel.home-ops.yansyah.my.id
      - op: replace
        path: /spec/template/spec/containers/0/args/7
        value: --cookie-domain=.home-ops.yansyah.my.id
      - op: replace
        path: /spec/template/spec/containers/0/args/16
        value: --redirect-url=https://hubble.home-ops.yansyah.my.id/oauth2/callback
    target:
      kind: Deployment
      name: oauth2-proxy
