apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tuwunel-secrets.yaml
  - wildcard-certificate.yaml
  - bucketclaims.yaml
  - cosi-keys.yaml
  - tuwunel.yaml
  - tuwunel-vpa.yaml
  - tuwunel-httproute.yaml
